name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  frontend:
    name: Frontend CI/CD
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Navigate to Frontend Directory
      run: cd AirbusInventory

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Frontend Dependencies
      run: npm install

    - name: Print current directory
      run: pwd
    - name: List files in directory
      run: ls -al

    #- name: Check if package.json exists
     # run: test -f package.json
    - name: Navigate to Frontend Directory
      run: cd AirbusInventory
      
    - name: Build Angular App
      run: npm run build
      working-directory: AirbusInventory


  backend:
    name: Backend CI/CD
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'adopt'

    - name: Navigate to Backend Directory
      run: cd airbus-management-spring

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Run Backend Unit Tests
      run: mvn test

    - name: Deploy Backend
      run: |
        # Add commands to deploy the backend application (assuming it's packaged as a JAR file)
        # For example: java -jar target/your-application.jar
